remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "FactorIA"
description: "An Intelligent Assistant for the game Factorio <img src='/FactorIA/assets/images/factorio.ico' alt='Factorio Logo' style='vertical-align:middle;margin-left:0px;box-shadow:none;padding:0;border:none;max-height:20px;'>"
